### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by Sogl** [smaxwellstewart/hapi-dash#12]
Hi!

I did all from your instructions, but can't run server:
```
MacBook-Air-Artem:hapi-dash artyom$ node bin/start.js
module.js:339
    throw err;
    ^

Error: Cannot find module '../config'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/artyom/projects/hapi/hapi-dash/bin/start.js:2:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
MacBook-Air-Artem:hapi-dash artyom$ node servers/api/server.js
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
module.js:339
    throw err;
    ^

Error: Cannot find module '../../config'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/artyom/projects/hapi/hapi-dash/servers/api/server.js:7:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
MacBook-Air-Artem:hapi-dash artyom$
```

Env:
```
OS X 10.10.5
node 4.2.1
npm 3.3.12
```

Any chance to see this project working with last hapi.js and other modules version?

**Comment by smaxwellstewart** [comment]
Looks like it might be a problem with node v4. Will make it work with the latest modules.

**Comment by Sogl** [comment]
What I need to do? 

Update all `packages.json` module to latest? Would it works after?

**Comment by smaxwellstewart** [comment]
@Sogl I am in the process of updating all the packages. I am now changing some code that is incompatible with new versions.  Hopefully I will have a fix soon!
